name: Build GEO Asset
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Build GEOIP
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./geoip-build/go.mod
          cache-dependency-path: ./geoip-build/go.sum
        env:
          GOPATH: /tmp/go-geoip-build

      - name: Update Go dependencies for GEOIP
        working-directory: ./geoip-build
        run: go mod tidy

      - name: Set variables
        run: |
          # Set timezone to Asia/Jakarta
          export TZ="Asia/Jakarta"
          echo "TAG_NAME=$(date +'%d%m%Y-%H%M')" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +'%d%m%Y-%H%M')" >> $GITHUB_ENV
          echo "OISD_SMALL=https://small.oisd.nl/dnsmasq" >> $GITHUB_ENV
        shell: bash

      - name: Download GeoLite2 databases
        env:
          LICENSE_KEY: ${{ secrets.MAXMIND_GEOLITE2_LICENSE }}
        run: |
          mkdir -p publish
          mkdir -p output
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${LICENSE_KEY}&suffix=tar.gz" -o ./geoip-build/asset/GeoLite2-ASN.tar.gz
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN-CSV&license_key=${LICENSE_KEY}&suffix=zip" -o ./geoip-build/asset/GeoLite2-ASN-CSV.zip
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${LICENSE_KEY}&suffix=tar.gz" -o ./geoip-build/asset/GeoLite2-Country.tar.gz
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=${LICENSE_KEY}&suffix=zip" -o ./geoip-build/asset/GeoLite2-Country-CSV.zip

      # Push downloaded GeoLite2 files
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add and Commit Changes
        run: |
          git add geoip-build/asset/{*.gz,*.zip}
          git commit -m "Add updated GeoLite2 asset"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push

      - name: Prepare GeoLite2 databases
        run: |
          cd geoip-build
          cp ./asset/* ../output/
          mkdir -p geolite2
          cp ../output/{*.gz,*.zip} ./
          
          unzip GeoLite2-Country-CSV.zip
          unzip GeoLite2-ASN-CSV.zip
          tar -xvzf GeoLite2-Country.tar.gz
          tar -xvzf GeoLite2-ASN.tar.gz
          
          cp GeoLite2-Country_*/*.mmdb ../output/
          cp GeoLite2-ASN_*/*.mmdb ../output/
          cp GeoLite2-Country-CSV_*/{GeoLite2-Country-Blocks-*,GeoLite2-Country-Locations-en}.csv ../output/
          cp GeoLite2-ASN-CSV_*/*.csv ../output/

          cp GeoLite2-Country-CSV_*/*.csv ./geolite2/
          cp GeoLite2-ASN-CSV_*/*.csv ./geolite2/

      - name: Build geoip files
        run: |
          cd ./geoip-build/
          go build ./
          ./geoip convert -c ./config.json

      - name: Verify mmdb files
        run: |
          cd ./output || exit 1
          go install -v github.com/maxmind/mmdbverify@latest
          for name in $(ls *.mmdb); do
            $(go env GOPATH)/bin/mmdbverify -file ${name}
          done

      # Build GEOSITE
      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: v2fly/domain-list-community
          path: community

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./geosite-build/go.mod
          cache-dependency-path: ./geosite-build/go.sum
        env:
          GOPATH: /tmp/go-geosite-build

      - name: Update Go dependencies for GEOSITE
        working-directory: ./geosite-build
        run: go mod tidy

      - name: Create lists
        run: |
          #curl -sSL $OISD_SMALL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-small
          curl -sSL $OISD_SMALL | perl -ne '/^server=\/([^\/]+)\// && $1 !~ /^(googlesyndication\.com|pagead2\.googlesyndication\.com)$/ && print "$1\n"' > ./community/data/oisd-small

      - name: Build geosite.dat file
        run: |
          cd geosite-build
          go run ./ --datapath=../community/data

      - name: Move files
        run: |
          install -Dp ./output/geoip.dat ./publish/GeoIP.dat
          install -Dp ./output/Country.mmdb ./publish/Country.mmdb
          install -Dp ./output/GeoLite2-ASN.mmdb ./publish/GeoLite2-ASN.mmdb
          install -Dp ./geosite-build/publish/geosite.dat ./publish/GeoSite.dat

      - name: Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done

      - name: Delete Old Release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          repo: KhoirulAmsori/geoasset
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



