name: Build GEO Asset
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup environment & download asset
        run: |
          export TZ="Asia/Jakarta"
          echo "TAG_NAME=$(date +'%d%m%Y-%H%M')" >> $GITHUB_ENV
          echo "BUILDTIME=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
          echo "OISD_SMALL=https://small.oisd.nl/dnsmasq" >> $GITHUB_ENV
          echo "OISD_NSFW=https://nsfw.oisd.nl/dnsmasq" >> $GITHUB_ENV
          echo "OISD_NSFW_SMALL=https://nsfw-small.oisd.nl/dnsmasq" >> $GITHUB_ENV
          git clone --depth 1 -b asset https://github.com/${{ github.repository }} geoip-build/asset

      # Build GEOIP
      - name: Build GEOIP
        uses: actions/setup-go@v5
        with:
          go-version-file: ./geoip-build/go.mod
          cache-dependency-path: ./geoip-build/go.sum
        env:
          GOPATH: /tmp/go-geoip-build
        run: |
          cd geoip-build/asset
          for file in *.{tar.gz,zip}; do
            [[ $file == *.tar.gz ]] && tar -xvzf "$file"
            [[ $file == *.zip ]] && unzip "$file"
          done
          cd ..
          mkdir -p geolite2
          cp asset/GeoLite2-Country_*/*.mmdb geolite2/
          cp asset/GeoLite2-ASN_*/*.mmdb geolite2/
          cp asset/GeoLite2-ASN-CSV_*/*.csv geolite2/
          cp asset/GeoLite2-Country-CSV_*/*.csv geolite2/
          cp asset/GeoLite2-Country-CSV_*/{GeoLite2-Country-Blocks-IPv4*,GeoLite2-Country-Locations-en}.csv geolite2/
          go mod tidy
          go build ./
          ./geoip convert -c ./config.json

      # Build GEOSITE
      - name: Build GEOSITE
        uses: actions/setup-go@v5
        with:
          go-version-file: ./geosite-build/go.mod
          cache-dependency-path: ./geosite-build/go.sum
        env:
          GOPATH: /tmp/go-geosite-build
        run: |
          git clone --depth 1 https://github.com/v2fly/domain-list-community community
          cd geosite-build
          go mod tidy
          curl -sSL $OISD_SMALL | perl -ne 'if(/^server=\/([^\/]+)\//){$d=$1;if($d!~/^(googlesyndication\.com|pagead2\.googlesyndication\.com|gambar123\.com)$/){print "$d\n"}}' > ../community/data/oisd-small
          exclude=$(paste -sd'|' exclude_list.txt)
          curl -sSL $OISD_NSFW_SMALL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' | grep -vE "$exclude" > ../community/data/oisd-nsfw-small
          cp raven_nsfw ../community/data/raven_nsfw
          go run ./ --datapath=../community/data

      # Build Sing-Box asset
      - name: Build Sing-Box assets
        run: |
          git clone --depth 1 https://github.com/MetaCubeX/meta-rules-converter convert
          mkdir -p sing-rule/geo/{geosite,geoip} sing-rule/asn
          curl -s -o nice.rsc http://ixp.mikrotik.co.id/download/nice.rsc
          echo '{"version":4,"rules":[{"ip_cidr":[' > nice.json
          grep -oP 'address="\K[0-9./]+' nice.rsc | grep '/' | sed 's/.*/"&",/' >> nice.json
          sed -i '$ s/,$//' nice.json
          echo ']}]}' >> nice.json
          cp nice.json ./publish/nice.json
          curl -fsSL https://sing-box.app/install.sh | sh -s -- --beta
          sing-box rule-set compile --output ./publish/nice.srs nice.json
          cd convert
          go run ./ geosite -f ../geosite-build/publish/geosite.dat -o ../sing-rule/geo/geosite -t sing-box
          go run ./ geoip -f ../publish/GeoIP.dat -o ../sing-rule/geo/geoip -t sing-box
          cp ../geoip-build/geolite2/GeoLite2-ASN.mmdb ./asn/
          go run ./ asn -o ../sing-rule/asn -t sing-box

      # Push sing-rule branch
      - name: Push sing-box branch
        run: |
          cd sing-rule
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b sing-box
          git add .
          git commit -m "Released on ${{ env.BUILDTIME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin sing-box

      - name: Move final assets
        run: |
          install -Dp ./geoip-build/geolite2/GeoLite2-ASN.mmdb ./publish/GeoLite2-ASN.mmdb
          install -Dp ./geosite-build/publish/geosite.dat ./publish/GeoSite.dat

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ env.BUILDTIME }}
          tag: latest
          file_glob: true
          overwrite: true
          file: ./publish/*
